#!/bin/bash

echo "🔥 MNTRK Firebase Service Account Setup"
echo "======================================"
echo ""
echo "STEP 1: Generate Service Account Key"
echo "1. Go to: https://console.firebase.google.com/project/mntrk-fcd2b/settings/serviceaccounts/adminsdk"
echo "2. Click 'Generate new private key'"
echo "3. Download the JSON file"
echo "4. Save it as 'firebase-credentials.json'"
echo ""
echo "STEP 2: Set Environment Variable"
echo "export FIREBASE_CREDENTIALS=/path/to/firebase-credentials.json"
echo ""
echo "STEP 3: Test Connection"
echo "python setup/real_firebase_test.py"
echo ""
echo "🛡️ Your Firebase Project: mntrk-fcd2b"
echo "📁 Storage Bucket: mntrk-fcd2b.firebasestorage.app"
