# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApinotificationssubscribeSmartThresholds(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, auto_calibrated: bool=None, recent_anomaly_window: str=None):  # noqa: E501
        """ApinotificationssubscribeSmartThresholds - a model defined in Swagger

        :param auto_calibrated: The auto_calibrated of this ApinotificationssubscribeSmartThresholds.  # noqa: E501
        :type auto_calibrated: bool
        :param recent_anomaly_window: The recent_anomaly_window of this ApinotificationssubscribeSmartThresholds.  # noqa: E501
        :type recent_anomaly_window: str
        """
        self.swagger_types = {
            'auto_calibrated': bool,
            'recent_anomaly_window': str
        }

        self.attribute_map = {
            'auto_calibrated': 'auto_calibrated',
            'recent_anomaly_window': 'recent_anomaly_window'
        }
        self._auto_calibrated = auto_calibrated
        self._recent_anomaly_window = recent_anomaly_window

    @classmethod
    def from_dict(cls, dikt) -> 'ApinotificationssubscribeSmartThresholds':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The apinotificationssubscribe_smart_thresholds of this ApinotificationssubscribeSmartThresholds.  # noqa: E501
        :rtype: ApinotificationssubscribeSmartThresholds
        """
        return util.deserialize_model(dikt, cls)

    @property
    def auto_calibrated(self) -> bool:
        """Gets the auto_calibrated of this ApinotificationssubscribeSmartThresholds.


        :return: The auto_calibrated of this ApinotificationssubscribeSmartThresholds.
        :rtype: bool
        """
        return self._auto_calibrated

    @auto_calibrated.setter
    def auto_calibrated(self, auto_calibrated: bool):
        """Sets the auto_calibrated of this ApinotificationssubscribeSmartThresholds.


        :param auto_calibrated: The auto_calibrated of this ApinotificationssubscribeSmartThresholds.
        :type auto_calibrated: bool
        """

        self._auto_calibrated = auto_calibrated

    @property
    def recent_anomaly_window(self) -> str:
        """Gets the recent_anomaly_window of this ApinotificationssubscribeSmartThresholds.

        Time window for dynamic threshold recalibration (e.g., \"7d\")  # noqa: E501

        :return: The recent_anomaly_window of this ApinotificationssubscribeSmartThresholds.
        :rtype: str
        """
        return self._recent_anomaly_window

    @recent_anomaly_window.setter
    def recent_anomaly_window(self, recent_anomaly_window: str):
        """Sets the recent_anomaly_window of this ApinotificationssubscribeSmartThresholds.

        Time window for dynamic threshold recalibration (e.g., \"7d\")  # noqa: E501

        :param recent_anomaly_window: The recent_anomaly_window of this ApinotificationssubscribeSmartThresholds.
        :type recent_anomaly_window: str
        """

        self._recent_anomaly_window = recent_anomaly_window
