# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DetectionPatternResponseEnvironmentalContext(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: float=None, humidity: float=None, vegetation_density: float=None):  # noqa: E501
        """DetectionPatternResponseEnvironmentalContext - a model defined in Swagger

        :param temperature: The temperature of this DetectionPatternResponseEnvironmentalContext.  # noqa: E501
        :type temperature: float
        :param humidity: The humidity of this DetectionPatternResponseEnvironmentalContext.  # noqa: E501
        :type humidity: float
        :param vegetation_density: The vegetation_density of this DetectionPatternResponseEnvironmentalContext.  # noqa: E501
        :type vegetation_density: float
        """
        self.swagger_types = {
            'temperature': float,
            'humidity': float,
            'vegetation_density': float
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'humidity': 'humidity',
            'vegetation_density': 'vegetation_density'
        }
        self._temperature = temperature
        self._humidity = humidity
        self._vegetation_density = vegetation_density

    @classmethod
    def from_dict(cls, dikt) -> 'DetectionPatternResponseEnvironmentalContext':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DetectionPatternResponse_environmental_context of this DetectionPatternResponseEnvironmentalContext.  # noqa: E501
        :rtype: DetectionPatternResponseEnvironmentalContext
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> float:
        """Gets the temperature of this DetectionPatternResponseEnvironmentalContext.


        :return: The temperature of this DetectionPatternResponseEnvironmentalContext.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this DetectionPatternResponseEnvironmentalContext.


        :param temperature: The temperature of this DetectionPatternResponseEnvironmentalContext.
        :type temperature: float
        """

        self._temperature = temperature

    @property
    def humidity(self) -> float:
        """Gets the humidity of this DetectionPatternResponseEnvironmentalContext.


        :return: The humidity of this DetectionPatternResponseEnvironmentalContext.
        :rtype: float
        """
        return self._humidity

    @humidity.setter
    def humidity(self, humidity: float):
        """Sets the humidity of this DetectionPatternResponseEnvironmentalContext.


        :param humidity: The humidity of this DetectionPatternResponseEnvironmentalContext.
        :type humidity: float
        """

        self._humidity = humidity

    @property
    def vegetation_density(self) -> float:
        """Gets the vegetation_density of this DetectionPatternResponseEnvironmentalContext.


        :return: The vegetation_density of this DetectionPatternResponseEnvironmentalContext.
        :rtype: float
        """
        return self._vegetation_density

    @vegetation_density.setter
    def vegetation_density(self, vegetation_density: float):
        """Sets the vegetation_density of this DetectionPatternResponseEnvironmentalContext.


        :param vegetation_density: The vegetation_density of this DetectionPatternResponseEnvironmentalContext.
        :type vegetation_density: float
        """

        self._vegetation_density = vegetation_density
