# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GoogleVisionResponseObjects(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, bounding_box: object=None):  # noqa: E501
        """GoogleVisionResponseObjects - a model defined in Swagger

        :param name: The name of this GoogleVisionResponseObjects.  # noqa: E501
        :type name: str
        :param bounding_box: The bounding_box of this GoogleVisionResponseObjects.  # noqa: E501
        :type bounding_box: object
        """
        self.swagger_types = {
            'name': str,
            'bounding_box': object
        }

        self.attribute_map = {
            'name': 'name',
            'bounding_box': 'bounding_box'
        }
        self._name = name
        self._bounding_box = bounding_box

    @classmethod
    def from_dict(cls, dikt) -> 'GoogleVisionResponseObjects':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoogleVisionResponse_objects of this GoogleVisionResponseObjects.  # noqa: E501
        :rtype: GoogleVisionResponseObjects
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this GoogleVisionResponseObjects.


        :return: The name of this GoogleVisionResponseObjects.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GoogleVisionResponseObjects.


        :param name: The name of this GoogleVisionResponseObjects.
        :type name: str
        """

        self._name = name

    @property
    def bounding_box(self) -> object:
        """Gets the bounding_box of this GoogleVisionResponseObjects.


        :return: The bounding_box of this GoogleVisionResponseObjects.
        :rtype: object
        """
        return self._bounding_box

    @bounding_box.setter
    def bounding_box(self, bounding_box: object):
        """Sets the bounding_box of this GoogleVisionResponseObjects.


        :param bounding_box: The bounding_box of this GoogleVisionResponseObjects.
        :type bounding_box: object
        """

        self._bounding_box = bounding_box
