# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HabitatAnalysisRequestEnvironmentalData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, temperature: float=None, rainfall: float=None, vegetation_index: float=None):  # noqa: E501
        """HabitatAnalysisRequestEnvironmentalData - a model defined in Swagger

        :param temperature: The temperature of this HabitatAnalysisRequestEnvironmentalData.  # noqa: E501
        :type temperature: float
        :param rainfall: The rainfall of this HabitatAnalysisRequestEnvironmentalData.  # noqa: E501
        :type rainfall: float
        :param vegetation_index: The vegetation_index of this HabitatAnalysisRequestEnvironmentalData.  # noqa: E501
        :type vegetation_index: float
        """
        self.swagger_types = {
            'temperature': float,
            'rainfall': float,
            'vegetation_index': float
        }

        self.attribute_map = {
            'temperature': 'temperature',
            'rainfall': 'rainfall',
            'vegetation_index': 'vegetation_index'
        }
        self._temperature = temperature
        self._rainfall = rainfall
        self._vegetation_index = vegetation_index

    @classmethod
    def from_dict(cls, dikt) -> 'HabitatAnalysisRequestEnvironmentalData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HabitatAnalysisRequest_environmental_data of this HabitatAnalysisRequestEnvironmentalData.  # noqa: E501
        :rtype: HabitatAnalysisRequestEnvironmentalData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temperature(self) -> float:
        """Gets the temperature of this HabitatAnalysisRequestEnvironmentalData.


        :return: The temperature of this HabitatAnalysisRequestEnvironmentalData.
        :rtype: float
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature: float):
        """Sets the temperature of this HabitatAnalysisRequestEnvironmentalData.


        :param temperature: The temperature of this HabitatAnalysisRequestEnvironmentalData.
        :type temperature: float
        """

        self._temperature = temperature

    @property
    def rainfall(self) -> float:
        """Gets the rainfall of this HabitatAnalysisRequestEnvironmentalData.


        :return: The rainfall of this HabitatAnalysisRequestEnvironmentalData.
        :rtype: float
        """
        return self._rainfall

    @rainfall.setter
    def rainfall(self, rainfall: float):
        """Sets the rainfall of this HabitatAnalysisRequestEnvironmentalData.


        :param rainfall: The rainfall of this HabitatAnalysisRequestEnvironmentalData.
        :type rainfall: float
        """

        self._rainfall = rainfall

    @property
    def vegetation_index(self) -> float:
        """Gets the vegetation_index of this HabitatAnalysisRequestEnvironmentalData.


        :return: The vegetation_index of this HabitatAnalysisRequestEnvironmentalData.
        :rtype: float
        """
        return self._vegetation_index

    @vegetation_index.setter
    def vegetation_index(self, vegetation_index: float):
        """Sets the vegetation_index of this HabitatAnalysisRequestEnvironmentalData.


        :param vegetation_index: The vegetation_index of this HabitatAnalysisRequestEnvironmentalData.
        :type vegetation_index: float
        """

        self._vegetation_index = vegetation_index
