# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PredictiveModelResponseConfidenceExplanationShapScores(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, feature: str=None, importance: float=None):  # noqa: E501
        """PredictiveModelResponseConfidenceExplanationShapScores - a model defined in Swagger

        :param feature: The feature of this PredictiveModelResponseConfidenceExplanationShapScores.  # noqa: E501
        :type feature: str
        :param importance: The importance of this PredictiveModelResponseConfidenceExplanationShapScores.  # noqa: E501
        :type importance: float
        """
        self.swagger_types = {
            'feature': str,
            'importance': float
        }

        self.attribute_map = {
            'feature': 'feature',
            'importance': 'importance'
        }
        self._feature = feature
        self._importance = importance

    @classmethod
    def from_dict(cls, dikt) -> 'PredictiveModelResponseConfidenceExplanationShapScores':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictiveModelResponse_confidence_explanation_shap_scores of this PredictiveModelResponseConfidenceExplanationShapScores.  # noqa: E501
        :rtype: PredictiveModelResponseConfidenceExplanationShapScores
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feature(self) -> str:
        """Gets the feature of this PredictiveModelResponseConfidenceExplanationShapScores.


        :return: The feature of this PredictiveModelResponseConfidenceExplanationShapScores.
        :rtype: str
        """
        return self._feature

    @feature.setter
    def feature(self, feature: str):
        """Sets the feature of this PredictiveModelResponseConfidenceExplanationShapScores.


        :param feature: The feature of this PredictiveModelResponseConfidenceExplanationShapScores.
        :type feature: str
        """

        self._feature = feature

    @property
    def importance(self) -> float:
        """Gets the importance of this PredictiveModelResponseConfidenceExplanationShapScores.


        :return: The importance of this PredictiveModelResponseConfidenceExplanationShapScores.
        :rtype: float
        """
        return self._importance

    @importance.setter
    def importance(self, importance: float):
        """Sets the importance of this PredictiveModelResponseConfidenceExplanationShapScores.


        :param importance: The importance of this PredictiveModelResponseConfidenceExplanationShapScores.
        :type importance: float
        """

        self._importance = importance
