# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PredictiveModelRequestMultiSourceFeatures(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sentinel_ndvi_7d_avg: float=None, rainfall_sensor_last_3d: float=None, known_outbreak_density: float=None):  # noqa: E501
        """PredictiveModelRequestMultiSourceFeatures - a model defined in Swagger

        :param sentinel_ndvi_7d_avg: The sentinel_ndvi_7d_avg of this PredictiveModelRequestMultiSourceFeatures.  # noqa: E501
        :type sentinel_ndvi_7d_avg: float
        :param rainfall_sensor_last_3d: The rainfall_sensor_last_3d of this PredictiveModelRequestMultiSourceFeatures.  # noqa: E501
        :type rainfall_sensor_last_3d: float
        :param known_outbreak_density: The known_outbreak_density of this PredictiveModelRequestMultiSourceFeatures.  # noqa: E501
        :type known_outbreak_density: float
        """
        self.swagger_types = {
            'sentinel_ndvi_7d_avg': float,
            'rainfall_sensor_last_3d': float,
            'known_outbreak_density': float
        }

        self.attribute_map = {
            'sentinel_ndvi_7d_avg': 'sentinel_ndvi_7d_avg',
            'rainfall_sensor_last_3d': 'rainfall_sensor_last_3d',
            'known_outbreak_density': 'known_outbreak_density'
        }
        self._sentinel_ndvi_7d_avg = sentinel_ndvi_7d_avg
        self._rainfall_sensor_last_3d = rainfall_sensor_last_3d
        self._known_outbreak_density = known_outbreak_density

    @classmethod
    def from_dict(cls, dikt) -> 'PredictiveModelRequestMultiSourceFeatures':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictiveModelRequest_multi_source_features of this PredictiveModelRequestMultiSourceFeatures.  # noqa: E501
        :rtype: PredictiveModelRequestMultiSourceFeatures
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sentinel_ndvi_7d_avg(self) -> float:
        """Gets the sentinel_ndvi_7d_avg of this PredictiveModelRequestMultiSourceFeatures.


        :return: The sentinel_ndvi_7d_avg of this PredictiveModelRequestMultiSourceFeatures.
        :rtype: float
        """
        return self._sentinel_ndvi_7d_avg

    @sentinel_ndvi_7d_avg.setter
    def sentinel_ndvi_7d_avg(self, sentinel_ndvi_7d_avg: float):
        """Sets the sentinel_ndvi_7d_avg of this PredictiveModelRequestMultiSourceFeatures.


        :param sentinel_ndvi_7d_avg: The sentinel_ndvi_7d_avg of this PredictiveModelRequestMultiSourceFeatures.
        :type sentinel_ndvi_7d_avg: float
        """

        self._sentinel_ndvi_7d_avg = sentinel_ndvi_7d_avg

    @property
    def rainfall_sensor_last_3d(self) -> float:
        """Gets the rainfall_sensor_last_3d of this PredictiveModelRequestMultiSourceFeatures.


        :return: The rainfall_sensor_last_3d of this PredictiveModelRequestMultiSourceFeatures.
        :rtype: float
        """
        return self._rainfall_sensor_last_3d

    @rainfall_sensor_last_3d.setter
    def rainfall_sensor_last_3d(self, rainfall_sensor_last_3d: float):
        """Sets the rainfall_sensor_last_3d of this PredictiveModelRequestMultiSourceFeatures.


        :param rainfall_sensor_last_3d: The rainfall_sensor_last_3d of this PredictiveModelRequestMultiSourceFeatures.
        :type rainfall_sensor_last_3d: float
        """

        self._rainfall_sensor_last_3d = rainfall_sensor_last_3d

    @property
    def known_outbreak_density(self) -> float:
        """Gets the known_outbreak_density of this PredictiveModelRequestMultiSourceFeatures.


        :return: The known_outbreak_density of this PredictiveModelRequestMultiSourceFeatures.
        :rtype: float
        """
        return self._known_outbreak_density

    @known_outbreak_density.setter
    def known_outbreak_density(self, known_outbreak_density: float):
        """Sets the known_outbreak_density of this PredictiveModelRequestMultiSourceFeatures.


        :param known_outbreak_density: The known_outbreak_density of this PredictiveModelRequestMultiSourceFeatures.
        :type known_outbreak_density: float
        """

        self._known_outbreak_density = known_outbreak_density
