# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vision_analyze_response_detections import VisionAnalyzeResponseDetections  # noqa: F401,E501
from swagger_server.models.vision_analyze_response_extracted_features import VisionAnalyzeResponseExtractedFeatures  # noqa: F401,E501
from swagger_server import util


class VisionAnalyzeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, detections: List[VisionAnalyzeResponseDetections]=None, extracted_features: VisionAnalyzeResponseExtractedFeatures=None):  # noqa: E501
        """VisionAnalyzeResponse - a model defined in Swagger

        :param status: The status of this VisionAnalyzeResponse.  # noqa: E501
        :type status: str
        :param detections: The detections of this VisionAnalyzeResponse.  # noqa: E501
        :type detections: List[VisionAnalyzeResponseDetections]
        :param extracted_features: The extracted_features of this VisionAnalyzeResponse.  # noqa: E501
        :type extracted_features: VisionAnalyzeResponseExtractedFeatures
        """
        self.swagger_types = {
            'status': str,
            'detections': List[VisionAnalyzeResponseDetections],
            'extracted_features': VisionAnalyzeResponseExtractedFeatures
        }

        self.attribute_map = {
            'status': 'status',
            'detections': 'detections',
            'extracted_features': 'extracted_features'
        }
        self._status = status
        self._detections = detections
        self._extracted_features = extracted_features

    @classmethod
    def from_dict(cls, dikt) -> 'VisionAnalyzeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisionAnalyzeResponse of this VisionAnalyzeResponse.  # noqa: E501
        :rtype: VisionAnalyzeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this VisionAnalyzeResponse.


        :return: The status of this VisionAnalyzeResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this VisionAnalyzeResponse.


        :param status: The status of this VisionAnalyzeResponse.
        :type status: str
        """

        self._status = status

    @property
    def detections(self) -> List[VisionAnalyzeResponseDetections]:
        """Gets the detections of this VisionAnalyzeResponse.


        :return: The detections of this VisionAnalyzeResponse.
        :rtype: List[VisionAnalyzeResponseDetections]
        """
        return self._detections

    @detections.setter
    def detections(self, detections: List[VisionAnalyzeResponseDetections]):
        """Sets the detections of this VisionAnalyzeResponse.


        :param detections: The detections of this VisionAnalyzeResponse.
        :type detections: List[VisionAnalyzeResponseDetections]
        """

        self._detections = detections

    @property
    def extracted_features(self) -> VisionAnalyzeResponseExtractedFeatures:
        """Gets the extracted_features of this VisionAnalyzeResponse.


        :return: The extracted_features of this VisionAnalyzeResponse.
        :rtype: VisionAnalyzeResponseExtractedFeatures
        """
        return self._extracted_features

    @extracted_features.setter
    def extracted_features(self, extracted_features: VisionAnalyzeResponseExtractedFeatures):
        """Sets the extracted_features of this VisionAnalyzeResponse.


        :param extracted_features: The extracted_features of this VisionAnalyzeResponse.
        :type extracted_features: VisionAnalyzeResponseExtractedFeatures
        """

        self._extracted_features = extracted_features
