# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VisionAnalyzeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image: str=None, confidence_threshold: float=None):  # noqa: E501
        """VisionAnalyzeRequest - a model defined in Swagger

        :param image: The image of this VisionAnalyzeRequest.  # noqa: E501
        :type image: str
        :param confidence_threshold: The confidence_threshold of this VisionAnalyzeRequest.  # noqa: E501
        :type confidence_threshold: float
        """
        self.swagger_types = {
            'image': str,
            'confidence_threshold': float
        }

        self.attribute_map = {
            'image': 'image',
            'confidence_threshold': 'confidence_threshold'
        }
        self._image = image
        self._confidence_threshold = confidence_threshold

    @classmethod
    def from_dict(cls, dikt) -> 'VisionAnalyzeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisionAnalyzeRequest of this VisionAnalyzeRequest.  # noqa: E501
        :rtype: VisionAnalyzeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> str:
        """Gets the image of this VisionAnalyzeRequest.


        :return: The image of this VisionAnalyzeRequest.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this VisionAnalyzeRequest.


        :param image: The image of this VisionAnalyzeRequest.
        :type image: str
        """

        self._image = image

    @property
    def confidence_threshold(self) -> float:
        """Gets the confidence_threshold of this VisionAnalyzeRequest.


        :return: The confidence_threshold of this VisionAnalyzeRequest.
        :rtype: float
        """
        return self._confidence_threshold

    @confidence_threshold.setter
    def confidence_threshold(self, confidence_threshold: float):
        """Sets the confidence_threshold of this VisionAnalyzeRequest.


        :param confidence_threshold: The confidence_threshold of this VisionAnalyzeRequest.
        :type confidence_threshold: float
        """

        self._confidence_threshold = confidence_threshold
