# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataManagementTransformResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, transformed_data_url: Object=None):  # noqa: E501
        """DataManagementTransformResponse - a model defined in Swagger

        :param transformed_data_url: The transformed_data_url of this DataManagementTransformResponse.  # noqa: E501
        :type transformed_data_url: Object
        """
        self.swagger_types = {
            'transformed_data_url': Object
        }

        self.attribute_map = {
            'transformed_data_url': 'transformed_data_url'
        }
        self._transformed_data_url = transformed_data_url

    @classmethod
    def from_dict(cls, dikt) -> 'DataManagementTransformResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataManagementTransformResponse of this DataManagementTransformResponse.  # noqa: E501
        :rtype: DataManagementTransformResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def transformed_data_url(self) -> Object:
        """Gets the transformed_data_url of this DataManagementTransformResponse.

        URL to the transformed dataset.  # noqa: E501

        :return: The transformed_data_url of this DataManagementTransformResponse.
        :rtype: Object
        """
        return self._transformed_data_url

    @transformed_data_url.setter
    def transformed_data_url(self, transformed_data_url: Object):
        """Sets the transformed_data_url of this DataManagementTransformResponse.

        URL to the transformed dataset.  # noqa: E501

        :param transformed_data_url: The transformed_data_url of this DataManagementTransformResponse.
        :type transformed_data_url: Object
        """

        self._transformed_data_url = transformed_data_url
