# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IoTIngestResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: Object=None, processed_data: Object=None):  # noqa: E501
        """IoTIngestResponse - a model defined in Swagger

        :param status: The status of this IoTIngestResponse.  # noqa: E501
        :type status: Object
        :param processed_data: The processed_data of this IoTIngestResponse.  # noqa: E501
        :type processed_data: Object
        """
        self.swagger_types = {
            'status': Object,
            'processed_data': Object
        }

        self.attribute_map = {
            'status': 'status',
            'processed_data': 'processed_data'
        }
        self._status = status
        self._processed_data = processed_data

    @classmethod
    def from_dict(cls, dikt) -> 'IoTIngestResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IoTIngestResponse of this IoTIngestResponse.  # noqa: E501
        :rtype: IoTIngestResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> Object:
        """Gets the status of this IoTIngestResponse.

        Status of the ingestion process.  # noqa: E501

        :return: The status of this IoTIngestResponse.
        :rtype: Object
        """
        return self._status

    @status.setter
    def status(self, status: Object):
        """Sets the status of this IoTIngestResponse.

        Status of the ingestion process.  # noqa: E501

        :param status: The status of this IoTIngestResponse.
        :type status: Object
        """

        self._status = status

    @property
    def processed_data(self) -> Object:
        """Gets the processed_data of this IoTIngestResponse.

        Preprocessed and validated sensor data.  # noqa: E501

        :return: The processed_data of this IoTIngestResponse.
        :rtype: Object
        """
        return self._processed_data

    @processed_data.setter
    def processed_data(self, processed_data: Object):
        """Sets the processed_data of this IoTIngestResponse.

        Preprocessed and validated sensor data.  # noqa: E501

        :param processed_data: The processed_data of this IoTIngestResponse.
        :type processed_data: Object
        """

        self._processed_data = processed_data
