# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RAGQueryRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, query: Object=None):  # noqa: E501
        """RAGQueryRequest - a model defined in Swagger

        :param query: The query of this RAGQueryRequest.  # noqa: E501
        :type query: Object
        """
        self.swagger_types = {
            'query': Object
        }

        self.attribute_map = {
            'query': 'query'
        }
        self._query = query

    @classmethod
    def from_dict(cls, dikt) -> 'RAGQueryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RAGQueryRequest of this RAGQueryRequest.  # noqa: E501
        :rtype: RAGQueryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> Object:
        """Gets the query of this RAGQueryRequest.

        The user query to process.  # noqa: E501

        :return: The query of this RAGQueryRequest.
        :rtype: Object
        """
        return self._query

    @query.setter
    def query(self, query: Object):
        """Sets the query of this RAGQueryRequest.

        The user query to process.  # noqa: E501

        :param query: The query of this RAGQueryRequest.
        :type query: Object
        """

        self._query = query
