# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GoogleVisionResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, labels: object=None, objects: object=None, text: object=None):  # noqa: E501
        """GoogleVisionResponse - a model defined in Swagger

        :param labels: The labels of this GoogleVisionResponse.  # noqa: E501
        :type labels: object
        :param objects: The objects of this GoogleVisionResponse.  # noqa: E501
        :type objects: object
        :param text: The text of this GoogleVisionResponse.  # noqa: E501
        :type text: object
        """
        self.swagger_types = {
            'labels': object,
            'objects': object,
            'text': object
        }

        self.attribute_map = {
            'labels': 'labels',
            'objects': 'objects',
            'text': 'text'
        }
        self._labels = labels
        self._objects = objects
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'GoogleVisionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoogleVisionResponse of this GoogleVisionResponse.  # noqa: E501
        :rtype: GoogleVisionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def labels(self) -> object:
        """Gets the labels of this GoogleVisionResponse.

        Detected labels  # noqa: E501

        :return: The labels of this GoogleVisionResponse.
        :rtype: object
        """
        return self._labels

    @labels.setter
    def labels(self, labels: object):
        """Sets the labels of this GoogleVisionResponse.

        Detected labels  # noqa: E501

        :param labels: The labels of this GoogleVisionResponse.
        :type labels: object
        """

        self._labels = labels

    @property
    def objects(self) -> object:
        """Gets the objects of this GoogleVisionResponse.


        :return: The objects of this GoogleVisionResponse.
        :rtype: object
        """
        return self._objects

    @objects.setter
    def objects(self, objects: object):
        """Sets the objects of this GoogleVisionResponse.


        :param objects: The objects of this GoogleVisionResponse.
        :type objects: object
        """

        self._objects = objects

    @property
    def text(self) -> object:
        """Gets the text of this GoogleVisionResponse.

        Detected text  # noqa: E501

        :return: The text of this GoogleVisionResponse.
        :rtype: object
        """
        return self._text

    @text.setter
    def text(self, text: object):
        """Sets the text of this GoogleVisionResponse.

        Detected text  # noqa: E501

        :param text: The text of this GoogleVisionResponse.
        :type text: object
        """

        self._text = text
