# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RemoteSensingAugmentationResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: object=None, results_url: object=None):  # noqa: E501
        """RemoteSensingAugmentationResponse - a model defined in Swagger

        :param message: The message of this RemoteSensingAugmentationResponse.  # noqa: E501
        :type message: object
        :param results_url: The results_url of this RemoteSensingAugmentationResponse.  # noqa: E501
        :type results_url: object
        """
        self.swagger_types = {
            'message': object,
            'results_url': object
        }

        self.attribute_map = {
            'message': 'message',
            'results_url': 'results_url'
        }
        self._message = message
        self._results_url = results_url

    @classmethod
    def from_dict(cls, dikt) -> 'RemoteSensingAugmentationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RemoteSensingAugmentationResponse of this RemoteSensingAugmentationResponse.  # noqa: E501
        :rtype: RemoteSensingAugmentationResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> object:
        """Gets the message of this RemoteSensingAugmentationResponse.


        :return: The message of this RemoteSensingAugmentationResponse.
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message: object):
        """Sets the message of this RemoteSensingAugmentationResponse.


        :param message: The message of this RemoteSensingAugmentationResponse.
        :type message: object
        """

        self._message = message

    @property
    def results_url(self) -> object:
        """Gets the results_url of this RemoteSensingAugmentationResponse.


        :return: The results_url of this RemoteSensingAugmentationResponse.
        :rtype: object
        """
        return self._results_url

    @results_url.setter
    def results_url(self, results_url: object):
        """Sets the results_url of this RemoteSensingAugmentationResponse.


        :param results_url: The results_url of this RemoteSensingAugmentationResponse.
        :type results_url: object
        """

        self._results_url = results_url
