# coding: utf-8

# flake8: noqa
from __future__ import absolute_import
# import models into model package
from swagger_server.models.adaptive_learning_request import AdaptiveLearningRequest
from swagger_server.models.adaptive_learning_response import AdaptiveLearningResponse
from swagger_server.models.anomaly_detection_request import AnomalyDetectionRequest
from swagger_server.models.anomaly_detection_response import AnomalyDetectionResponse
from swagger_server.models.data_transformation_request import DataTransformationRequest
from swagger_server.models.data_transformation_response import DataTransformationResponse
from swagger_server.models.detection_pattern import DetectionPattern
from swagger_server.models.detection_pattern_response import DetectionPatternResponse
from swagger_server.models.google_vision_request import GoogleVisionRequest
from swagger_server.models.google_vision_response import GoogleVisionResponse
from swagger_server.models.habitat_analysis_request import HabitatAnalysisRequest
from swagger_server.models.habitat_analysis_request_analysis_parameters import HabitatAnalysisRequestAnalysisParameters
from swagger_server.models.habitat_analysis_request_environmental_data import HabitatAnalysisRequestEnvironmentalData
from swagger_server.models.habitat_analysis_request_geographic_coordinates import HabitatAnalysisRequestGeographicCoordinates
from swagger_server.models.habitat_analysis_response import HabitatAnalysisResponse
from swagger_server.models.lang_chain_request import LangChainRequest
from swagger_server.models.lang_chain_response import LangChainResponse
from swagger_server.models.movement_prediction_response import MovementPredictionResponse
from swagger_server.models.postgres_query_request import PostgresQueryRequest
from swagger_server.models.postgres_query_response import PostgresQueryResponse
from swagger_server.models.predictive_model_request import PredictiveModelRequest
from swagger_server.models.predictive_model_response import PredictiveModelResponse
from swagger_server.models.remote_sensing_augmentation_request import RemoteSensingAugmentationRequest
from swagger_server.models.remote_sensing_augmentation_response import RemoteSensingAugmentationResponse
from swagger_server.models.supabase_query_request import SupabaseQueryRequest
from swagger_server.models.supabase_query_response import SupabaseQueryResponse
from swagger_server.models.vision_analyze_request import VisionAnalyzeRequest
from swagger_server.models.vision_analyze_response import VisionAnalyzeResponse
