# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnomalyDetectionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_file: Object=None, detection_method: Object=None):  # noqa: E501
        """AnomalyDetectionRequest - a model defined in Swagger

        :param input_file: The input_file of this AnomalyDetectionRequest.  # noqa: E501
        :type input_file: Object
        :param detection_method: The detection_method of this AnomalyDetectionRequest.  # noqa: E501
        :type detection_method: Object
        """
        self.swagger_types = {
            'input_file': Object,
            'detection_method': Object
        }

        self.attribute_map = {
            'input_file': 'input_file',
            'detection_method': 'detection_method'
        }
        self._input_file = input_file
        self._detection_method = detection_method

    @classmethod
    def from_dict(cls, dikt) -> 'AnomalyDetectionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnomalyDetectionRequest of this AnomalyDetectionRequest.  # noqa: E501
        :rtype: AnomalyDetectionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_file(self) -> Object:
        """Gets the input_file of this AnomalyDetectionRequest.


        :return: The input_file of this AnomalyDetectionRequest.
        :rtype: Object
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file: Object):
        """Sets the input_file of this AnomalyDetectionRequest.


        :param input_file: The input_file of this AnomalyDetectionRequest.
        :type input_file: Object
        """

        self._input_file = input_file

    @property
    def detection_method(self) -> Object:
        """Gets the detection_method of this AnomalyDetectionRequest.


        :return: The detection_method of this AnomalyDetectionRequest.
        :rtype: Object
        """
        return self._detection_method

    @detection_method.setter
    def detection_method(self, detection_method: Object):
        """Sets the detection_method of this AnomalyDetectionRequest.


        :param detection_method: The detection_method of this AnomalyDetectionRequest.
        :type detection_method: Object
        """

        self._detection_method = detection_method
