# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataTransformationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dataset_url: Object=None):  # noqa: E501
        """DataTransformationRequest - a model defined in Swagger

        :param dataset_url: The dataset_url of this DataTransformationRequest.  # noqa: E501
        :type dataset_url: Object
        """
        self.swagger_types = {
            'dataset_url': Object
        }

        self.attribute_map = {
            'dataset_url': 'dataset_url'
        }
        self._dataset_url = dataset_url

    @classmethod
    def from_dict(cls, dikt) -> 'DataTransformationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataTransformationRequest of this DataTransformationRequest.  # noqa: E501
        :rtype: DataTransformationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dataset_url(self) -> Object:
        """Gets the dataset_url of this DataTransformationRequest.


        :return: The dataset_url of this DataTransformationRequest.
        :rtype: Object
        """
        return self._dataset_url

    @dataset_url.setter
    def dataset_url(self, dataset_url: Object):
        """Sets the dataset_url of this DataTransformationRequest.


        :param dataset_url: The dataset_url of this DataTransformationRequest.
        :type dataset_url: Object
        """

        self._dataset_url = dataset_url
