# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GoogleVisionRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image: Object=None, features: Object=None):  # noqa: E501
        """GoogleVisionRequest - a model defined in Swagger

        :param image: The image of this GoogleVisionRequest.  # noqa: E501
        :type image: Object
        :param features: The features of this GoogleVisionRequest.  # noqa: E501
        :type features: Object
        """
        self.swagger_types = {
            'image': Object,
            'features': Object
        }

        self.attribute_map = {
            'image': 'image',
            'features': 'features'
        }
        self._image = image
        self._features = features

    @classmethod
    def from_dict(cls, dikt) -> 'GoogleVisionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GoogleVisionRequest of this GoogleVisionRequest.  # noqa: E501
        :rtype: GoogleVisionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> Object:
        """Gets the image of this GoogleVisionRequest.

        Base64-encoded image data  # noqa: E501

        :return: The image of this GoogleVisionRequest.
        :rtype: Object
        """
        return self._image

    @image.setter
    def image(self, image: Object):
        """Sets the image of this GoogleVisionRequest.

        Base64-encoded image data  # noqa: E501

        :param image: The image of this GoogleVisionRequest.
        :type image: Object
        """

        self._image = image

    @property
    def features(self) -> Object:
        """Gets the features of this GoogleVisionRequest.

        Google Vision features to analyze (e.g., LABEL_DETECTION)  # noqa: E501

        :return: The features of this GoogleVisionRequest.
        :rtype: Object
        """
        return self._features

    @features.setter
    def features(self, features: Object):
        """Sets the features of this GoogleVisionRequest.

        Google Vision features to analyze (e.g., LABEL_DETECTION)  # noqa: E501

        :param features: The features of this GoogleVisionRequest.
        :type features: Object
        """

        self._features = features
