# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.habitat_analysis_request_geographic_coordinates import HabitatAnalysisRequestGeographicCoordinates  # noqa: F401,E501
from swagger_server import util


class HabitatAnalysisResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: Object=None, location: HabitatAnalysisRequestGeographicCoordinates=None, suitability_score: Object=None):  # noqa: E501
        """HabitatAnalysisResponse - a model defined in Swagger

        :param id: The id of this HabitatAnalysisResponse.  # noqa: E501
        :type id: Object
        :param location: The location of this HabitatAnalysisResponse.  # noqa: E501
        :type location: HabitatAnalysisRequestGeographicCoordinates
        :param suitability_score: The suitability_score of this HabitatAnalysisResponse.  # noqa: E501
        :type suitability_score: Object
        """
        self.swagger_types = {
            'id': Object,
            'location': HabitatAnalysisRequestGeographicCoordinates,
            'suitability_score': Object
        }

        self.attribute_map = {
            'id': 'id',
            'location': 'location',
            'suitability_score': 'suitability_score'
        }
        self._id = id
        self._location = location
        self._suitability_score = suitability_score

    @classmethod
    def from_dict(cls, dikt) -> 'HabitatAnalysisResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HabitatAnalysisResponse of this HabitatAnalysisResponse.  # noqa: E501
        :rtype: HabitatAnalysisResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> Object:
        """Gets the id of this HabitatAnalysisResponse.


        :return: The id of this HabitatAnalysisResponse.
        :rtype: Object
        """
        return self._id

    @id.setter
    def id(self, id: Object):
        """Sets the id of this HabitatAnalysisResponse.


        :param id: The id of this HabitatAnalysisResponse.
        :type id: Object
        """

        self._id = id

    @property
    def location(self) -> HabitatAnalysisRequestGeographicCoordinates:
        """Gets the location of this HabitatAnalysisResponse.


        :return: The location of this HabitatAnalysisResponse.
        :rtype: HabitatAnalysisRequestGeographicCoordinates
        """
        return self._location

    @location.setter
    def location(self, location: HabitatAnalysisRequestGeographicCoordinates):
        """Sets the location of this HabitatAnalysisResponse.


        :param location: The location of this HabitatAnalysisResponse.
        :type location: HabitatAnalysisRequestGeographicCoordinates
        """

        self._location = location

    @property
    def suitability_score(self) -> Object:
        """Gets the suitability_score of this HabitatAnalysisResponse.


        :return: The suitability_score of this HabitatAnalysisResponse.
        :rtype: Object
        """
        return self._suitability_score

    @suitability_score.setter
    def suitability_score(self, suitability_score: Object):
        """Sets the suitability_score of this HabitatAnalysisResponse.


        :param suitability_score: The suitability_score of this HabitatAnalysisResponse.
        :type suitability_score: Object
        """

        self._suitability_score = suitability_score
