# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HabitatAnalysisRequestAnalysisParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vegetation_threshold: Object=None):  # noqa: E501
        """HabitatAnalysisRequestAnalysisParameters - a model defined in Swagger

        :param vegetation_threshold: The vegetation_threshold of this HabitatAnalysisRequestAnalysisParameters.  # noqa: E501
        :type vegetation_threshold: Object
        """
        self.swagger_types = {
            'vegetation_threshold': Object
        }

        self.attribute_map = {
            'vegetation_threshold': 'vegetation_threshold'
        }
        self._vegetation_threshold = vegetation_threshold

    @classmethod
    def from_dict(cls, dikt) -> 'HabitatAnalysisRequestAnalysisParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HabitatAnalysisRequest_analysis_parameters of this HabitatAnalysisRequestAnalysisParameters.  # noqa: E501
        :rtype: HabitatAnalysisRequestAnalysisParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vegetation_threshold(self) -> Object:
        """Gets the vegetation_threshold of this HabitatAnalysisRequestAnalysisParameters.


        :return: The vegetation_threshold of this HabitatAnalysisRequestAnalysisParameters.
        :rtype: Object
        """
        return self._vegetation_threshold

    @vegetation_threshold.setter
    def vegetation_threshold(self, vegetation_threshold: Object):
        """Sets the vegetation_threshold of this HabitatAnalysisRequestAnalysisParameters.


        :param vegetation_threshold: The vegetation_threshold of this HabitatAnalysisRequestAnalysisParameters.
        :type vegetation_threshold: Object
        """

        self._vegetation_threshold = vegetation_threshold
