# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LangChainRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, prompt: Object=None, options: Object=None):  # noqa: E501
        """LangChainRequest - a model defined in Swagger

        :param prompt: The prompt of this LangChainRequest.  # noqa: E501
        :type prompt: Object
        :param options: The options of this LangChainRequest.  # noqa: E501
        :type options: Object
        """
        self.swagger_types = {
            'prompt': Object,
            'options': Object
        }

        self.attribute_map = {
            'prompt': 'prompt',
            'options': 'options'
        }
        self._prompt = prompt
        self._options = options

    @classmethod
    def from_dict(cls, dikt) -> 'LangChainRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LangChainRequest of this LangChainRequest.  # noqa: E501
        :rtype: LangChainRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prompt(self) -> Object:
        """Gets the prompt of this LangChainRequest.

        Input prompt for LangChain  # noqa: E501

        :return: The prompt of this LangChainRequest.
        :rtype: Object
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt: Object):
        """Sets the prompt of this LangChainRequest.

        Input prompt for LangChain  # noqa: E501

        :param prompt: The prompt of this LangChainRequest.
        :type prompt: Object
        """

        self._prompt = prompt

    @property
    def options(self) -> Object:
        """Gets the options of this LangChainRequest.

        Additional options for generating insights  # noqa: E501

        :return: The options of this LangChainRequest.
        :rtype: Object
        """
        return self._options

    @options.setter
    def options(self, options: Object):
        """Sets the options of this LangChainRequest.

        Additional options for generating insights  # noqa: E501

        :param options: The options of this LangChainRequest.
        :type options: Object
        """

        self._options = options
