# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LangChainResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, generated_text: Object=None, metadata: Object=None):  # noqa: E501
        """LangChainResponse - a model defined in Swagger

        :param generated_text: The generated_text of this LangChainResponse.  # noqa: E501
        :type generated_text: Object
        :param metadata: The metadata of this LangChainResponse.  # noqa: E501
        :type metadata: Object
        """
        self.swagger_types = {
            'generated_text': Object,
            'metadata': Object
        }

        self.attribute_map = {
            'generated_text': 'generated_text',
            'metadata': 'metadata'
        }
        self._generated_text = generated_text
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'LangChainResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LangChainResponse of this LangChainResponse.  # noqa: E501
        :rtype: LangChainResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def generated_text(self) -> Object:
        """Gets the generated_text of this LangChainResponse.

        Text generated by LangChain  # noqa: E501

        :return: The generated_text of this LangChainResponse.
        :rtype: Object
        """
        return self._generated_text

    @generated_text.setter
    def generated_text(self, generated_text: Object):
        """Sets the generated_text of this LangChainResponse.

        Text generated by LangChain  # noqa: E501

        :param generated_text: The generated_text of this LangChainResponse.
        :type generated_text: Object
        """

        self._generated_text = generated_text

    @property
    def metadata(self) -> Object:
        """Gets the metadata of this LangChainResponse.

        Metadata related to the generation process  # noqa: E501

        :return: The metadata of this LangChainResponse.
        :rtype: Object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Object):
        """Sets the metadata of this LangChainResponse.

        Metadata related to the generation process  # noqa: E501

        :param metadata: The metadata of this LangChainResponse.
        :type metadata: Object
        """

        self._metadata = metadata
