# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PostgresQueryRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, query: Object=None, parameters: Object=None):  # noqa: E501
        """PostgresQueryRequest - a model defined in Swagger

        :param query: The query of this PostgresQueryRequest.  # noqa: E501
        :type query: Object
        :param parameters: The parameters of this PostgresQueryRequest.  # noqa: E501
        :type parameters: Object
        """
        self.swagger_types = {
            'query': Object,
            'parameters': Object
        }

        self.attribute_map = {
            'query': 'query',
            'parameters': 'parameters'
        }
        self._query = query
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'PostgresQueryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostgresQueryRequest of this PostgresQueryRequest.  # noqa: E501
        :rtype: PostgresQueryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def query(self) -> Object:
        """Gets the query of this PostgresQueryRequest.

        SQL query to execute on Postgres  # noqa: E501

        :return: The query of this PostgresQueryRequest.
        :rtype: Object
        """
        return self._query

    @query.setter
    def query(self, query: Object):
        """Sets the query of this PostgresQueryRequest.

        SQL query to execute on Postgres  # noqa: E501

        :param query: The query of this PostgresQueryRequest.
        :type query: Object
        """

        self._query = query

    @property
    def parameters(self) -> Object:
        """Gets the parameters of this PostgresQueryRequest.

        Parameters for the SQL query  # noqa: E501

        :return: The parameters of this PostgresQueryRequest.
        :rtype: Object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: Object):
        """Sets the parameters of this PostgresQueryRequest.

        Parameters for the SQL query  # noqa: E501

        :param parameters: The parameters of this PostgresQueryRequest.
        :type parameters: Object
        """

        self._parameters = parameters
