# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PredictiveModelResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: Object=None, predictions: Object=None):  # noqa: E501
        """PredictiveModelResponse - a model defined in Swagger

        :param status: The status of this PredictiveModelResponse.  # noqa: E501
        :type status: Object
        :param predictions: The predictions of this PredictiveModelResponse.  # noqa: E501
        :type predictions: Object
        """
        self.swagger_types = {
            'status': Object,
            'predictions': Object
        }

        self.attribute_map = {
            'status': 'status',
            'predictions': 'predictions'
        }
        self._status = status
        self._predictions = predictions

    @classmethod
    def from_dict(cls, dikt) -> 'PredictiveModelResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PredictiveModelResponse of this PredictiveModelResponse.  # noqa: E501
        :rtype: PredictiveModelResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> Object:
        """Gets the status of this PredictiveModelResponse.


        :return: The status of this PredictiveModelResponse.
        :rtype: Object
        """
        return self._status

    @status.setter
    def status(self, status: Object):
        """Sets the status of this PredictiveModelResponse.


        :param status: The status of this PredictiveModelResponse.
        :type status: Object
        """

        self._status = status

    @property
    def predictions(self) -> Object:
        """Gets the predictions of this PredictiveModelResponse.


        :return: The predictions of this PredictiveModelResponse.
        :rtype: Object
        """
        return self._predictions

    @predictions.setter
    def predictions(self, predictions: Object):
        """Sets the predictions of this PredictiveModelResponse.


        :param predictions: The predictions of this PredictiveModelResponse.
        :type predictions: Object
        """

        self._predictions = predictions
