# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SupabaseQueryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Object=None, metadata: Object=None):  # noqa: E501
        """SupabaseQueryResponse - a model defined in Swagger

        :param data: The data of this SupabaseQueryResponse.  # noqa: E501
        :type data: Object
        :param metadata: The metadata of this SupabaseQueryResponse.  # noqa: E501
        :type metadata: Object
        """
        self.swagger_types = {
            'data': Object,
            'metadata': Object
        }

        self.attribute_map = {
            'data': 'data',
            'metadata': 'metadata'
        }
        self._data = data
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'SupabaseQueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SupabaseQueryResponse of this SupabaseQueryResponse.  # noqa: E501
        :rtype: SupabaseQueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Object:
        """Gets the data of this SupabaseQueryResponse.

        Query results  # noqa: E501

        :return: The data of this SupabaseQueryResponse.
        :rtype: Object
        """
        return self._data

    @data.setter
    def data(self, data: Object):
        """Sets the data of this SupabaseQueryResponse.

        Query results  # noqa: E501

        :param data: The data of this SupabaseQueryResponse.
        :type data: Object
        """

        self._data = data

    @property
    def metadata(self) -> Object:
        """Gets the metadata of this SupabaseQueryResponse.

        Query execution metadata  # noqa: E501

        :return: The metadata of this SupabaseQueryResponse.
        :rtype: Object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Object):
        """Sets the metadata of this SupabaseQueryResponse.

        Query execution metadata  # noqa: E501

        :param metadata: The metadata of this SupabaseQueryResponse.
        :type metadata: Object
        """

        self._metadata = metadata
