# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class VisionAnalyzeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: Object=None, detections: Object=None):  # noqa: E501
        """VisionAnalyzeResponse - a model defined in Swagger

        :param status: The status of this VisionAnalyzeResponse.  # noqa: E501
        :type status: Object
        :param detections: The detections of this VisionAnalyzeResponse.  # noqa: E501
        :type detections: Object
        """
        self.swagger_types = {
            'status': Object,
            'detections': Object
        }

        self.attribute_map = {
            'status': 'status',
            'detections': 'detections'
        }
        self._status = status
        self._detections = detections

    @classmethod
    def from_dict(cls, dikt) -> 'VisionAnalyzeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisionAnalyzeResponse of this VisionAnalyzeResponse.  # noqa: E501
        :rtype: VisionAnalyzeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> Object:
        """Gets the status of this VisionAnalyzeResponse.


        :return: The status of this VisionAnalyzeResponse.
        :rtype: Object
        """
        return self._status

    @status.setter
    def status(self, status: Object):
        """Sets the status of this VisionAnalyzeResponse.


        :param status: The status of this VisionAnalyzeResponse.
        :type status: Object
        """

        self._status = status

    @property
    def detections(self) -> Object:
        """Gets the detections of this VisionAnalyzeResponse.


        :return: The detections of this VisionAnalyzeResponse.
        :rtype: Object
        """
        return self._detections

    @detections.setter
    def detections(self, detections: Object):
        """Sets the detections of this VisionAnalyzeResponse.


        :param detections: The detections of this VisionAnalyzeResponse.
        :type detections: Object
        """

        self._detections = detections
