# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict, Any  # Updated to include Any

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DataManagementOpenResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: Any=None):  # Updated to use Any
        """DataManagementOpenResponse - a model defined in Swagger

        :param message: The message of this DataManagementOpenResponse.  # noqa: E501
        :type message: Any
        """
        self.swagger_types = {
            'message': Any
        }

        self.attribute_map = {
            'message': 'message'
        }
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'DataManagementOpenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataManagementOpenResponse of this DataManagementOpenResponse.  # noqa: E501
        :rtype: DataManagementOpenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> Any:
        """Gets the message of this DataManagementOpenResponse.

        Confirmation of successful dataset loading.  # noqa: E501

        :return: The message of this DataManagementOpenResponse.
        :rtype: Any
        """
        return self._message

    @message.setter
    def message(self, message: Any):
        """Sets the message of this DataManagementOpenResponse.

        Confirmation of successful dataset loading.  # noqa: E501

        :param message: The message of this DataManagementOpenResponse.
        :type message: Any
        """

        self._message = message
