# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.explain_response_explanation import ExplainResponseExplanation  # noqa: F401,E501
from swagger_server import util


class ExplainResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, explanation: ExplainResponseExplanation=None):  # noqa: E501
        """ExplainResponse - a model defined in Swagger

        :param explanation: The explanation of this ExplainResponse.  # noqa: E501
        :type explanation: ExplainResponseExplanation
        """
        self.swagger_types = {
            'explanation': ExplainResponseExplanation
        }

        self.attribute_map = {
            'explanation': 'explanation'
        }
        self._explanation = explanation

    @classmethod
    def from_dict(cls, dikt) -> 'ExplainResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExplainResponse of this ExplainResponse.  # noqa: E501
        :rtype: ExplainResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def explanation(self) -> ExplainResponseExplanation:
        """Gets the explanation of this ExplainResponse.


        :return: The explanation of this ExplainResponse.
        :rtype: ExplainResponseExplanation
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation: ExplainResponseExplanation):
        """Sets the explanation of this ExplainResponse.


        :param explanation: The explanation of this ExplainResponse.
        :type explanation: ExplainResponseExplanation
        """

        self._explanation = explanation
