# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RiskAnalysisResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, risk_score: object=None, risk_factors: object=None):  # noqa: E501
        """RiskAnalysisResponse - a model defined in Swagger

        :param risk_score: The risk_score of this RiskAnalysisResponse.  # noqa: E501
        :type risk_score: object
        :param risk_factors: The risk_factors of this RiskAnalysisResponse.  # noqa: E501
        :type risk_factors: object
        """
        self.swagger_types = {
            'risk_score': object,
            'risk_factors': object
        }

        self.attribute_map = {
            'risk_score': 'risk_score',
            'risk_factors': 'risk_factors'
        }
        self._risk_score = risk_score
        self._risk_factors = risk_factors

    @classmethod
    def from_dict(cls, dikt) -> 'RiskAnalysisResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RiskAnalysisResponse of this RiskAnalysisResponse.  # noqa: E501
        :rtype: RiskAnalysisResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def risk_score(self) -> object:
        """Gets the risk_score of this RiskAnalysisResponse.

        Predicted risk score (0-1 scale).  # noqa: E501

        :return: The risk_score of this RiskAnalysisResponse.
        :rtype: object
        """
        return self._risk_score

    @risk_score.setter
    def risk_score(self, risk_score: object):
        """Sets the risk_score of this RiskAnalysisResponse.

        Predicted risk score (0-1 scale).  # noqa: E501

        :param risk_score: The risk_score of this RiskAnalysisResponse.
        :type risk_score: object
        """

        self._risk_score = risk_score

    @property
    def risk_factors(self) -> object:
        """Gets the risk_factors of this RiskAnalysisResponse.

        Key factors contributing to the predicted risk.  # noqa: E501

        :return: The risk_factors of this RiskAnalysisResponse.
        :rtype: object
        """
        return self._risk_factors

    @risk_factors.setter
    def risk_factors(self, risk_factors: object):
        """Sets the risk_factors of this RiskAnalysisResponse.

        Key factors contributing to the predicted risk.  # noqa: E501

        :param risk_factors: The risk_factors of this RiskAnalysisResponse.
        :type risk_factors: object
        """

        self._risk_factors = risk_factors
