# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DetectionPatternResponseDetections(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bounding_box: List[float]=None, confidence: float=None):  # noqa: E501
        """DetectionPatternResponseDetections - a model defined in Swagger

        :param bounding_box: The bounding_box of this DetectionPatternResponseDetections.  # noqa: E501
        :type bounding_box: List[float]
        :param confidence: The confidence of this DetectionPatternResponseDetections.  # noqa: E501
        :type confidence: float
        """
        self.swagger_types = {
            'bounding_box': List[float],
            'confidence': float
        }

        self.attribute_map = {
            'bounding_box': 'bounding_box',
            'confidence': 'confidence'
        }
        self._bounding_box = bounding_box
        self._confidence = confidence

    @classmethod
    def from_dict(cls, dikt) -> 'DetectionPatternResponseDetections':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DetectionPatternResponse_detections of this DetectionPatternResponseDetections.  # noqa: E501
        :rtype: DetectionPatternResponseDetections
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bounding_box(self) -> List[float]:
        """Gets the bounding_box of this DetectionPatternResponseDetections.

        Coordinates of the detected object (x_min, y_min, x_max, y_max).  # noqa: E501

        :return: The bounding_box of this DetectionPatternResponseDetections.
        :rtype: List[float]
        """
        return self._bounding_box

    @bounding_box.setter
    def bounding_box(self, bounding_box: List[float]):
        """Sets the bounding_box of this DetectionPatternResponseDetections.

        Coordinates of the detected object (x_min, y_min, x_max, y_max).  # noqa: E501

        :param bounding_box: The bounding_box of this DetectionPatternResponseDetections.
        :type bounding_box: List[float]
        """

        self._bounding_box = bounding_box

    @property
    def confidence(self) -> float:
        """Gets the confidence of this DetectionPatternResponseDetections.

        Confidence score of the detection (0-1).  # noqa: E501

        :return: The confidence of this DetectionPatternResponseDetections.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this DetectionPatternResponseDetections.

        Confidence score of the detection (0-1).  # noqa: E501

        :param confidence: The confidence of this DetectionPatternResponseDetections.
        :type confidence: float
        """

        self._confidence = confidence
