# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CommunityObservationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image_file: Object=None, video_file: Object=None, description: Object=None):  # noqa: E501
        """CommunityObservationRequest - a model defined in Swagger

        :param image_file: The image_file of this CommunityObservationRequest.  # noqa: E501
        :type image_file: Object
        :param video_file: The video_file of this CommunityObservationRequest.  # noqa: E501
        :type video_file: Object
        :param description: The description of this CommunityObservationRequest.  # noqa: E501
        :type description: Object
        """
        self.swagger_types = {
            'image_file': Object,
            'video_file': Object,
            'description': Object
        }

        self.attribute_map = {
            'image_file': 'image_file',
            'video_file': 'video_file',
            'description': 'description'
        }
        self._image_file = image_file
        self._video_file = video_file
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'CommunityObservationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CommunityObservationRequest of this CommunityObservationRequest.  # noqa: E501
        :rtype: CommunityObservationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_file(self) -> Object:
        """Gets the image_file of this CommunityObservationRequest.

        Image file of the observation.  # noqa: E501

        :return: The image_file of this CommunityObservationRequest.
        :rtype: Object
        """
        return self._image_file

    @image_file.setter
    def image_file(self, image_file: Object):
        """Sets the image_file of this CommunityObservationRequest.

        Image file of the observation.  # noqa: E501

        :param image_file: The image_file of this CommunityObservationRequest.
        :type image_file: Object
        """

        self._image_file = image_file

    @property
    def video_file(self) -> Object:
        """Gets the video_file of this CommunityObservationRequest.

        Video file of the observation.  # noqa: E501

        :return: The video_file of this CommunityObservationRequest.
        :rtype: Object
        """
        return self._video_file

    @video_file.setter
    def video_file(self, video_file: Object):
        """Sets the video_file of this CommunityObservationRequest.

        Video file of the observation.  # noqa: E501

        :param video_file: The video_file of this CommunityObservationRequest.
        :type video_file: Object
        """

        self._video_file = video_file

    @property
    def description(self) -> Object:
        """Gets the description of this CommunityObservationRequest.

        Additional details about the observation.  # noqa: E501

        :return: The description of this CommunityObservationRequest.
        :rtype: Object
        """
        return self._description

    @description.setter
    def description(self, description: Object):
        """Sets the description of this CommunityObservationRequest.

        Additional details about the observation.  # noqa: E501

        :param description: The description of this CommunityObservationRequest.
        :type description: Object
        """

        self._description = description
