# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DetectionPatternResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, detections: Object=None):  # noqa: E501
        """DetectionPatternResponse - a model defined in Swagger

        :param detections: The detections of this DetectionPatternResponse.  # noqa: E501
        :type detections: Object
        """
        self.swagger_types = {
            'detections': Object
        }

        self.attribute_map = {
            'detections': 'detections'
        }
        self._detections = detections

    @classmethod
    def from_dict(cls, dikt) -> 'DetectionPatternResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DetectionPatternResponse of this DetectionPatternResponse.  # noqa: E501
        :rtype: DetectionPatternResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detections(self) -> Object:
        """Gets the detections of this DetectionPatternResponse.

        List of detected objects and their metrics.  # noqa: E501

        :return: The detections of this DetectionPatternResponse.
        :rtype: Object
        """
        return self._detections

    @detections.setter
    def detections(self, detections: Object):
        """Sets the detections of this DetectionPatternResponse.

        List of detected objects and their metrics.  # noqa: E501

        :param detections: The detections of this DetectionPatternResponse.
        :type detections: Object
        """

        self._detections = detections
