# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GeospatialAnalysisRequestTimeRange(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_date: Object=None, end_date: Object=None):  # noqa: E501
        """GeospatialAnalysisRequestTimeRange - a model defined in Swagger

        :param start_date: The start_date of this GeospatialAnalysisRequestTimeRange.  # noqa: E501
        :type start_date: Object
        :param end_date: The end_date of this GeospatialAnalysisRequestTimeRange.  # noqa: E501
        :type end_date: Object
        """
        self.swagger_types = {
            'start_date': Object,
            'end_date': Object
        }

        self.attribute_map = {
            'start_date': 'start_date',
            'end_date': 'end_date'
        }
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'GeospatialAnalysisRequestTimeRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GeospatialAnalysisRequest_time_range of this GeospatialAnalysisRequestTimeRange.  # noqa: E501
        :rtype: GeospatialAnalysisRequestTimeRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self) -> Object:
        """Gets the start_date of this GeospatialAnalysisRequestTimeRange.

        Start date for the analysis.  # noqa: E501

        :return: The start_date of this GeospatialAnalysisRequestTimeRange.
        :rtype: Object
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: Object):
        """Sets the start_date of this GeospatialAnalysisRequestTimeRange.

        Start date for the analysis.  # noqa: E501

        :param start_date: The start_date of this GeospatialAnalysisRequestTimeRange.
        :type start_date: Object
        """

        self._start_date = start_date

    @property
    def end_date(self) -> Object:
        """Gets the end_date of this GeospatialAnalysisRequestTimeRange.

        End date for the analysis.  # noqa: E501

        :return: The end_date of this GeospatialAnalysisRequestTimeRange.
        :rtype: Object
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: Object):
        """Sets the end_date of this GeospatialAnalysisRequestTimeRange.

        End date for the analysis.  # noqa: E501

        :param end_date: The end_date of this GeospatialAnalysisRequestTimeRange.
        :type end_date: Object
        """

        self._end_date = end_date
