# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RiskAnalysisRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, region: Object=None, historical_data_url: Object=None):  # noqa: E501
        """RiskAnalysisRequest - a model defined in Swagger

        :param region: The region of this RiskAnalysisRequest.  # noqa: E501
        :type region: Object
        :param historical_data_url: The historical_data_url of this RiskAnalysisRequest.  # noqa: E501
        :type historical_data_url: Object
        """
        self.swagger_types = {
            'region': Object,
            'historical_data_url': Object
        }

        self.attribute_map = {
            'region': 'region',
            'historical_data_url': 'historical_data_url'
        }
        self._region = region
        self._historical_data_url = historical_data_url

    @classmethod
    def from_dict(cls, dikt) -> 'RiskAnalysisRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RiskAnalysisRequest of this RiskAnalysisRequest.  # noqa: E501
        :rtype: RiskAnalysisRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def region(self) -> Object:
        """Gets the region of this RiskAnalysisRequest.

        Target region for risk prediction.  # noqa: E501

        :return: The region of this RiskAnalysisRequest.
        :rtype: Object
        """
        return self._region

    @region.setter
    def region(self, region: Object):
        """Sets the region of this RiskAnalysisRequest.

        Target region for risk prediction.  # noqa: E501

        :param region: The region of this RiskAnalysisRequest.
        :type region: Object
        """

        self._region = region

    @property
    def historical_data_url(self) -> Object:
        """Gets the historical_data_url of this RiskAnalysisRequest.

        URL to historical population and outbreak data.  # noqa: E501

        :return: The historical_data_url of this RiskAnalysisRequest.
        :rtype: Object
        """
        return self._historical_data_url

    @historical_data_url.setter
    def historical_data_url(self, historical_data_url: Object):
        """Sets the historical_data_url of this RiskAnalysisRequest.

        URL to historical population and outbreak data.  # noqa: E501

        :param historical_data_url: The historical_data_url of this RiskAnalysisRequest.
        :type historical_data_url: Object
        """

        self._historical_data_url = historical_data_url
